workflows:
  my-workflow: # workflow ID
    name: Workflow test # workflow name displayed in Codemagic UI
    instance_type: mac_mini # machine instance type
    max_build_duration: 60 # build duration in minutes (min 1, max 120)
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Launch emulator
        script: flutter emulators --launch emulator
      - name: Run tests
        script: flutter drive --target test_driver/e2e.dart
      - name: Build for Android # Name of the section
        script: flutter build apk # The script(s) to be run in that section
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      scripts:
        - echo 'Post-publish script'
