workflows:
  my-workflow: # workflow ID
    name: Workflow test # workflow name displayed in Codemagic UI
    instance_type: mac_mini # machine instance type
    max_build_duration: 60 # build duration in minutes (min 1, max 120)
    environment:
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - name: Build for Android # Name of the section
        script: flutter build apk # The script(s) to be run in that section
      - name: Launch emulator
        script: flutter emulators --launch emulator
      - name: Run tests
        script: flutter drive --target test_driver/e2e.dart
    artifacts:
      - build/**/outputs/**/*.aab
    publishing:
      scripts:
        - echo 'Post-publish script'
