scripts:
  - name: Build for Android # Name of the section
    script: flutter build android # The script(s) to be run in that section
  - name: Launch emulator
    script: flutter emulators --launch emulator
  - name: Run tests
    script: flutter drive --target=test_driver/e2e.dart
